import type { Metadata } from "next";
import "./globals.css";
import Body from "@/COMPONENTS/Body";
import { Toaster } from "react-hot-toast";
import Providers from "./providers/SessionProvider";
import QueryProvider from "./providers/QueryProvider";


export const metadata: Metadata = {
  title: "Spektr Group CMMS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <Providers>
          <QueryProvider>
            <main className="flex h-screen overflow-hidden">
              <Body>
                {children}
                <Toaster />
              </Body>
            </main>
          </QueryProvider>
        </Providers>
      </body>
    </html>
  );
}
