import type { Metadata } from "next";
import "./globals.css";
import Body from "@/COMPONENTS/Body";
import { Toaster } from "react-hot-toast";
import Providers from "@/COMPONENTS/utils/providers";
import { SpeedInsights } from "@vercel/speed-insights/next"


export const metadata: Metadata = {
  title: "Spektr Group CMMS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <Providers>
          <SpeedInsights />
            {/* Removed overflow-hidden from main component */}
            <main className="flex h-screen overflow-x-hidden">
              <Body>
                {children}
                <Toaster />
              </Body>
            </main>
        </Providers>
      </body>
    </html>
  );
}
