import type { Metadata } from "next";
import "./globals.css";
import Body from "@/COMPONENTS/Body";
import { Toaster } from "react-hot-toast";
import Providers from "@/COMPONENTS/utils/providers";


export const metadata: Metadata = {
  title: "Spektr Group CMMS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let initialUser = null;
  try {
    const response = await fetch("/api/auth/me", {
      credentials: "include",
      cache: "no-store"
    });
    if (response.ok) initialUser = await response.json();
  } catch (error) {
    console.error("Error", error)
  }

  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <Providers initialUser={initialUser}>
            <main className="flex h-screen overflow-hidden">
              <Body>
                {children}
                <Toaster />
              </Body>
            </main>
        </Providers>
      </body>
    </html>
  );
}
